name: apy_estimation
author: valory
version: 0.1.0
description: A set of agents reaching consensus on APY estimates
aea_version: '>=1.0.0, <2.0.0'
license: Apache-2.0
fingerprint:
  README.md: bafybeibhbkelnxxvsln677imq65vgbglmlhyxtax4iqtzempjiwcoef3gq
fingerprint_ignore_patterns: []
agent: valory/apy_estimation:0.1.0:bafybeihddh5zumuvrb3mgszkpibv6sf566eyz5e6dmoaq77zwso5h5hd3e
number_of_agents: 4
deployment: {}
---
extra:
  setup_params:
    args:
      setup: &id001
        all_participants: ${ALL_PARTICIPANTS:list:["0x8d1D7b3cd99a3C35A481F069ec10513183d5d49E",
          "0x2c288d3f6FFC2548EC81808Fccbf7629352C49e4", "0xa6DB574Fc218F88508C225733ae9c07AC600B9Ae",
          "0x690f453Ca39ED23D5D8E481AddAea8b18fe0edB1"]}
        safe_contract_address: ${SAFE_CONTRACT_ADDRESS:str:0x0000000000000000000000000000000000000000}
        consensus_threshold: null
  deposit_endpoint:
    args: &id002
      url: ${SERVICE_APY_DEPOSIT_ENDPOINT:str:http://172.17.0.2:9999/apy/deposit}
public_id: valory/apy_estimation_chained_abci:0.1.0
type: skill
0:
  models:
    params:
      args:
        setup: *id001
        broadcast_to_server: true
        pair_ids:
          uniswap_subgraph:
          - '0xae461ca67b15dc8dc81ce7615e0320da1a9ab8d5'
          spooky_subgraph:
          - '0x2a651563c9d3af67ae0388a5c8f89b867038089e'
          - '0x2b4c76d0dc16be1c31d4c1dc53bf9b45987fc75c'
        n_observations: ${SERVICE_APY_N_OBSERVATIONS:int:120}
        history_end: null
        ipfs_domain_name: /dns/178.62.4.138/tcp/5001/http
        service_registry_address: ${SERVICE_REGISTRY_ADDRESS:str:null}
        share_tm_config_on_startup: ${SHARE_TM_CONFIG_ON_STARTUP:bool:false}
        on_chain_service_id: ${ON_CHAIN_SERVICE_ID:int:null}
        tendermint_p2p_url: ${TM_P2P_ENDPOINT_NODE_0:str:node0:26656}
    server_api:
      args: *id002
1:
  models:
    params:
      args:
        setup: *id001
        broadcast_to_server: true
        pair_ids:
          uniswap_subgraph:
          - '0xae461ca67b15dc8dc81ce7615e0320da1a9ab8d5'
          spooky_subgraph:
          - '0x2a651563c9d3af67ae0388a5c8f89b867038089e'
          - '0x2b4c76d0dc16be1c31d4c1dc53bf9b45987fc75c'
        n_observations: ${SERVICE_APY_N_OBSERVATIONS:int:120}
        history_end: null
        ipfs_domain_name: /dns/178.62.4.138/tcp/5001/http
        service_registry_address: ${SERVICE_REGISTRY_ADDRESS:str:null}
        share_tm_config_on_startup: ${SHARE_TM_CONFIG_ON_STARTUP:bool:false}
        on_chain_service_id: ${ON_CHAIN_SERVICE_ID:int:null}
        tendermint_p2p_url: ${TM_P2P_ENDPOINT_NODE_1:str:node1:26666}
    server_api:
      args: *id002
2:
  models:
    params:
      args:
        setup: *id001
        broadcast_to_server: true
        pair_ids:
          uniswap_subgraph:
          - '0xae461ca67b15dc8dc81ce7615e0320da1a9ab8d5'
          spooky_subgraph:
          - '0x2a651563c9d3af67ae0388a5c8f89b867038089e'
          - '0x2b4c76d0dc16be1c31d4c1dc53bf9b45987fc75c'
        n_observations: ${SERVICE_APY_N_OBSERVATIONS:int:120}
        history_end: null
        ipfs_domain_name: /dns/178.62.4.138/tcp/5001/http
        service_registry_address: ${SERVICE_REGISTRY_ADDRESS:str:null}
        share_tm_config_on_startup: ${SHARE_TM_CONFIG_ON_STARTUP:bool:false}
        on_chain_service_id: ${ON_CHAIN_SERVICE_ID:int:null}
        tendermint_p2p_url: ${TM_P2P_ENDPOINT_NODE_2:str:node2:26676}
    server_api:
      args: *id002
3:
  models:
    params:
      args:
        setup: *id001
        broadcast_to_server: true
        pair_ids:
          uniswap_subgraph:
          - '0xae461ca67b15dc8dc81ce7615e0320da1a9ab8d5'
          spooky_subgraph:
          - '0x2a651563c9d3af67ae0388a5c8f89b867038089e'
          - '0x2b4c76d0dc16be1c31d4c1dc53bf9b45987fc75c'
        n_observations: ${SERVICE_APY_N_OBSERVATIONS:int:120}
        history_end: null
        ipfs_domain_name: /dns/178.62.4.138/tcp/5001/http
        service_registry_address: ${SERVICE_REGISTRY_ADDRESS:str:null}
        share_tm_config_on_startup: ${SHARE_TM_CONFIG_ON_STARTUP:bool:false}
        on_chain_service_id: ${ON_CHAIN_SERVICE_ID:int:null}
        tendermint_p2p_url: ${TM_P2P_ENDPOINT_NODE_3:str:node3:26686}
    server_api:
      args: *id002
---
public_id: valory/ledger:0.19.0
type: connection
0:
  config:
    ledger_apis:
      ethereum:
        address: ${RPC_0:str:http://host.docker.internal:8545}
        chain_id: ${CHAIN_ID:int:1337}
        default_gas_price_strategy: eip1559
1:
  config:
    ledger_apis:
      ethereum:
        address: ${RPC_1:str:http://host.docker.internal:8545}
        chain_id: ${CHAIN_ID:int:1337}
        default_gas_price_strategy: eip1559
2:
  config:
    ledger_apis:
      ethereum:
        address: ${RPC_2:str:http://host.docker.internal:8545}
        chain_id: ${CHAIN_ID:int:1337}
        default_gas_price_strategy: eip1559
3:
  config:
    ledger_apis:
      ethereum:
        address: ${RPC_3:str:http://host.docker.internal:8545}
        chain_id: ${CHAIN_ID:int:1337}
        default_gas_price_strategy: eip1559
